# Generated by Django 6.0.4 on 2026-04-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(max_length=120)),
                ('brand', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='VND', max_length=10)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('safety_stock', models.PositiveIntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('weight_grams', models.PositiveIntegerField(default=0)),
                ('dimensions', models.JSONField(blank=True, default=dict)),
                ('color', models.CharField(blank=True, max_length=64)),
                ('material', models.CharField(blank=True, max_length=120)),
                ('size', models.CharField(blank=True, max_length=32)),
                ('origin_country', models.CharField(blank=True, max_length=120)),
                ('warranty_months', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('draft', 'Draft'), ('archived', 'Archived')], default='active', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
