from django.core.management.base import BaseCommand
from django.utils import timezone

from catalog.models import Product


PRODUCTS = [
    {"sku": "EL-1001", "name": "Laptop Pro 14", "slug": "laptop-pro-14", "category": "Electronics", "brand": "ZenTech", "price": 28990000, "discount_price": 26990000, "stock_quantity": 18, "safety_stock": 5, "rating": 4.8, "weight_grams": 1450, "dimensions": {"length_cm": 31.2, "width_cm": 22.1, "height_cm": 1.7}, "color": "Space Gray", "material": "Aluminum", "size": "14-inch", "origin_country": "China", "warranty_months": 24, "description": "Ultrabook cho dân văn phòng và developer.", "tags": ["laptop", "office", "premium"], "attributes": {"cpu": "Intel Core Ultra 7", "ram_gb": 32, "storage_gb": 1024}, "thumbnail_url": "https://example.com/products/laptop.jpg"},
    {"sku": "EL-1002", "name": "Wireless Earbuds AirBeat", "slug": "wireless-earbuds-airbeat", "category": "Electronics", "brand": "SoundMax", "price": 1990000, "discount_price": 1590000, "stock_quantity": 120, "safety_stock": 20, "rating": 4.5, "weight_grams": 58, "dimensions": {"length_cm": 6.3, "width_cm": 4.8, "height_cm": 2.6}, "color": "White", "material": "ABS", "size": "Compact", "origin_country": "Vietnam", "warranty_months": 12, "description": "Tai nghe true wireless chống ồn chủ động.", "tags": ["audio", "bluetooth", "travel"], "attributes": {"battery_hours": 28, "water_resistance": "IPX4"}, "thumbnail_url": "https://example.com/products/earbuds.jpg"},
    {"sku": "HM-2001", "name": "Ergo Office Chair", "slug": "ergo-office-chair", "category": "Home Office", "brand": "WorkEase", "price": 4590000, "discount_price": 3990000, "stock_quantity": 35, "safety_stock": 6, "rating": 4.7, "weight_grams": 17500, "dimensions": {"length_cm": 68, "width_cm": 68, "height_cm": 122}, "color": "Black", "material": "Mesh", "size": "Adjustable", "origin_country": "Malaysia", "warranty_months": 18, "description": "Ghế công thái học có đỡ thắt lưng.", "tags": ["chair", "office", "ergonomic"], "attributes": {"max_load_kg": 120, "armrest": "4D"}, "thumbnail_url": "https://example.com/products/chair.jpg"},
    {"sku": "FS-3001", "name": "Running Shoes Sprint X", "slug": "running-shoes-sprint-x", "category": "Fashion", "brand": "FlyStep", "price": 2290000, "discount_price": 1890000, "stock_quantity": 75, "safety_stock": 15, "rating": 4.6, "weight_grams": 620, "dimensions": {"length_cm": 32, "width_cm": 20, "height_cm": 12}, "color": "Blue", "material": "Knit", "size": "42", "origin_country": "Indonesia", "warranty_months": 6, "description": "Giày chạy bộ đệm êm, thoáng khí.", "tags": ["running", "sport", "men"], "attributes": {"sole": "Foam", "lace_type": "quick-lace"}, "thumbnail_url": "https://example.com/products/shoes.jpg"},
    {"sku": "BK-4001", "name": "Clean Architecture Handbook", "slug": "clean-architecture-handbook", "category": "Books", "brand": "TechPress", "price": 350000, "stock_quantity": 90, "safety_stock": 10, "rating": 4.9, "weight_grams": 480, "dimensions": {"length_cm": 23, "width_cm": 15, "height_cm": 2.5}, "color": "Multicolor", "material": "Paper", "size": "Paperback", "origin_country": "Vietnam", "warranty_months": 0, "description": "Sách kiến trúc phần mềm thực dụng.", "tags": ["book", "software", "backend"], "attributes": {"pages": 420, "language": "Vietnamese"}, "thumbnail_url": "https://example.com/products/book.jpg"},
    {"sku": "BT-5001", "name": "Stainless Water Bottle 1L", "slug": "stainless-water-bottle-1l", "category": "Lifestyle", "brand": "HydraGo", "price": 420000, "discount_price": 359000, "stock_quantity": 150, "safety_stock": 25, "rating": 4.4, "weight_grams": 390, "dimensions": {"length_cm": 8.5, "width_cm": 8.5, "height_cm": 30}, "color": "Green", "material": "Stainless Steel", "size": "1L", "origin_country": "Thailand", "warranty_months": 3, "description": "Bình giữ nhiệt cho dân công sở.", "tags": ["bottle", "eco", "daily"], "attributes": {"temperature_retention_hours": 12}, "thumbnail_url": "https://example.com/products/bottle.jpg"},
    {"sku": "EL-1003", "name": "Smartphone Nova 12", "slug": "smartphone-nova-12", "category": "Electronics", "brand": "Nova", "price": 17990000, "discount_price": 16990000, "stock_quantity": 42, "safety_stock": 8, "rating": 4.7, "weight_grams": 198, "dimensions": {"length_cm": 16.1, "width_cm": 7.4, "height_cm": 0.79}, "color": "Silver", "material": "Glass", "size": "6.7-inch", "origin_country": "Korea", "warranty_months": 12, "description": "Điện thoại flagship pin trâu.", "tags": ["smartphone", "5g", "camera"], "attributes": {"ram_gb": 12, "storage_gb": 256, "camera_mp": 50}, "thumbnail_url": "https://example.com/products/phone.jpg"},
    {"sku": "HM-2002", "name": "Air Fryer 6L", "slug": "air-fryer-6l", "category": "Home Appliance", "brand": "CookFast", "price": 2490000, "discount_price": 2190000, "stock_quantity": 27, "safety_stock": 4, "rating": 4.3, "weight_grams": 5400, "dimensions": {"length_cm": 35, "width_cm": 31, "height_cm": 34}, "color": "Black", "material": "Metal", "size": "6L", "origin_country": "China", "warranty_months": 12, "description": "Nồi chiên không dầu cho gia đình 4-6 người.", "tags": ["kitchen", "air-fryer", "family"], "attributes": {"power_watt": 1700, "temperature_range": "80-200C"}, "thumbnail_url": "https://example.com/products/air-fryer.jpg"},
    {"sku": "FS-3002", "name": "Minimalist Backpack", "slug": "minimalist-backpack", "category": "Fashion", "brand": "UrbanCarry", "price": 890000, "discount_price": 790000, "stock_quantity": 64, "safety_stock": 10, "rating": 4.5, "weight_grams": 780, "dimensions": {"length_cm": 30, "width_cm": 15, "height_cm": 45}, "color": "Khaki", "material": "Canvas", "size": "20L", "origin_country": "Vietnam", "warranty_months": 12, "description": "Balo công sở chống nước nhẹ.", "tags": ["backpack", "travel", "office"], "attributes": {"laptop_compartment": "15.6-inch", "waterproof": True}, "thumbnail_url": "https://example.com/products/backpack.jpg"},
    {"sku": "SP-6001", "name": "Yoga Mat Premium", "slug": "yoga-mat-premium", "category": "Sports", "brand": "FlexFit", "price": 650000, "discount_price": 549000, "stock_quantity": 88, "safety_stock": 12, "rating": 4.6, "weight_grams": 1100, "dimensions": {"length_cm": 183, "width_cm": 68, "height_cm": 0.6}, "color": "Purple", "material": "TPE", "size": "183x68cm", "origin_country": "Vietnam", "warranty_months": 1, "description": "Thảm yoga bám sàn tốt, không mùi.", "tags": ["yoga", "fitness", "home-workout"], "attributes": {"thickness_mm": 6, "strap_included": True}, "thumbnail_url": "https://example.com/products/yoga-mat.jpg"},
    {"sku": "FD-7001", "name": "Organic Arabica Coffee Beans", "slug": "organic-arabica-coffee-beans", "category": "Food", "brand": "Highland Farm", "price": 320000, "discount_price": 289000, "stock_quantity": 130, "safety_stock": 20, "rating": 4.8, "weight_grams": 500, "dimensions": {"length_cm": 20, "width_cm": 8, "height_cm": 32}, "color": "Brown", "material": "Coffee Beans", "size": "500g", "origin_country": "Vietnam", "warranty_months": 0, "description": "Cà phê hạt rang medium roast.", "tags": ["coffee", "organic", "beans"], "attributes": {"roast_level": "medium", "origin": "Da Lat"}, "thumbnail_url": "https://example.com/products/coffee.jpg"},
    {"sku": "TY-8001", "name": "STEM Robot Kit", "slug": "stem-robot-kit", "category": "Toys", "brand": "BrightKids", "price": 1190000, "discount_price": 990000, "stock_quantity": 40, "safety_stock": 6, "rating": 4.7, "weight_grams": 950, "dimensions": {"length_cm": 28, "width_cm": 24, "height_cm": 9}, "color": "Orange", "material": "ABS", "size": "Age 8+", "origin_country": "Singapore", "warranty_months": 3, "description": "Bộ lắp ráp robot lập trình cơ bản.", "tags": ["education", "robotics", "kids"], "attributes": {"pieces": 180, "battery": "AA x 4"}, "thumbnail_url": "https://example.com/products/robot-kit.jpg"},
]


class Command(BaseCommand):
    help = "Seed demo catalog with diverse product types."

    def handle(self, *args, **options):
        created = 0
        now = timezone.now()
        for payload in PRODUCTS:
            defaults = {**payload, "published_at": now}
            _, was_created = Product.objects.get_or_create(sku=payload["sku"], defaults=defaults)
            created += int(was_created)
        self.stdout.write(self.style.SUCCESS(f"Seeded products. Newly created: {created}"))
